<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-11-03T18:24:29 IST" name="Suite" finished-at="2020-11-03T18:26:34 IST" duration-ms="125720">
    <groups>
    </groups>
    <test started-at="2020-11-03T18:24:29 IST" name="test1" finished-at="2020-11-03T18:25:06 IST" duration-ms="37353">
      <class name="Test.APIUITest">
        <test-method signature="ValidateUIandAPIResult(java.lang.String)[pri:0, instance:Test.APIUITest@2bfc268b]" started-at="2020-11-03T18:24:42 IST" name="ValidateUIandAPIResult" finished-at="2020-11-03T18:25:06 IST" duration-ms="23573" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Allahabad]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Temperature is not with in variance range. UI value: 304.6111 | API value :297.21]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Temperature is not with in variance range. UI value: 304.6111 | API value :297.21
at Test.APIUITest.ValidateUIandAPIResult(APIUITest.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateUIandAPIResult -->
      </class> <!-- Test.APIUITest -->
    </test> <!-- test1 -->
    <test started-at="2020-11-03T18:25:07 IST" name="test2" finished-at="2020-11-03T18:25:34 IST" duration-ms="27123">
      <class name="Test.APIUITest">
        <test-method signature="ValidateUIandAPIResult(java.lang.String)[pri:0, instance:Test.APIUITest@932bc4a]" started-at="2020-11-03T18:25:22 IST" name="ValidateUIandAPIResult" finished-at="2020-11-03T18:25:34 IST" duration-ms="12140" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Bengaluru]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Temperature is not with in variance range. UI value: 302.3889 | API value :300.31]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Temperature is not with in variance range. UI value: 302.3889 | API value :300.31
at Test.APIUITest.ValidateUIandAPIResult(APIUITest.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateUIandAPIResult -->
      </class> <!-- Test.APIUITest -->
    </test> <!-- test2 -->
    <test started-at="2020-11-03T18:25:35 IST" name="test3" finished-at="2020-11-03T18:26:04 IST" duration-ms="29385">
      <class name="Test.UITest">
        <test-method signature="Validate_Weather_Functionality(java.lang.String)[pri:0, instance:Test.UITest@2df9b86]" started-at="2020-11-03T18:25:47 IST" name="Validate_Weather_Functionality" finished-at="2020-11-03T18:26:04 IST" duration-ms="16988" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Allahabad]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Validate_Weather_Functionality -->
      </class> <!-- Test.UITest -->
    </test> <!-- test3 -->
    <test started-at="2020-11-03T18:26:05 IST" name="test4" finished-at="2020-11-03T18:26:34 IST" duration-ms="28881">
      <class name="Test.UITest">
        <test-method signature="Validate_Weather_Functionality(java.lang.String)[pri:0, instance:Test.UITest@6babf3bf]" started-at="2020-11-03T18:26:18 IST" name="Validate_Weather_Functionality" finished-at="2020-11-03T18:26:34 IST" duration-ms="16557" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Lucknow]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Validate_Weather_Functionality -->
      </class> <!-- Test.UITest -->
    </test> <!-- test4 -->
  </suite> <!-- Suite -->
</testng-results>
